"""Adicionado campo 'language' na tabela Post

Revision ID: 7dda8731296f
Revises: ab0fc2359aa6
Create Date: 2022-04-11 18:12:39.442709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dda8731296f'
down_revision = 'ab0fc2359aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
